export default [
{
"login": "abhijit1990",
"id": 24940841,
"node_id": "MDQ6VXNlcjI0OTQwODQx",
"avatar_url": "https://avatars.githubusercontent.com/u/24940841?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/abhijit1990",
"html_url": "https://github.com/abhijit1990",
"followers_url": "https://api.github.com/users/abhijit1990/followers",
"following_url": "https://api.github.com/users/abhijit1990/following{/other_user}",
"gists_url": "https://api.github.com/users/abhijit1990/gists{/gist_id}",
"starred_url": "https://api.github.com/users/abhijit1990/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/abhijit1990/subscriptions",
"organizations_url": "https://api.github.com/users/abhijit1990/orgs",
"repos_url": "https://api.github.com/users/abhijit1990/repos",
"events_url": "https://api.github.com/users/abhijit1990/events{/privacy}",
"received_events_url": "https://api.github.com/users/abhijit1990/received_events",
"type": "User",
"site_admin": false
},
{
"login": "Roufida-saadallah29",
"id": 74608868,
"node_id": "MDQ6VXNlcjc0NjA4ODY4",
"avatar_url": "https://avatars.githubusercontent.com/u/74608868?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/Roufida-saadallah29",
"html_url": "https://github.com/Roufida-saadallah29",
"followers_url": "https://api.github.com/users/Roufida-saadallah29/followers",
"following_url": "https://api.github.com/users/Roufida-saadallah29/following{/other_user}",
"gists_url": "https://api.github.com/users/Roufida-saadallah29/gists{/gist_id}",
"starred_url": "https://api.github.com/users/Roufida-saadallah29/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/Roufida-saadallah29/subscriptions",
"organizations_url": "https://api.github.com/users/Roufida-saadallah29/orgs",
"repos_url": "https://api.github.com/users/Roufida-saadallah29/repos",
"events_url": "https://api.github.com/users/Roufida-saadallah29/events{/privacy}",
"received_events_url": "https://api.github.com/users/Roufida-saadallah29/received_events",
"type": "User",
"site_admin": false
},
{
"login": "mohdjaved291",
"id": 79897400,
"node_id": "MDQ6VXNlcjc5ODk3NDAw",
"avatar_url": "https://avatars.githubusercontent.com/u/79897400?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/mohdjaved291",
"html_url": "https://github.com/mohdjaved291",
"followers_url": "https://api.github.com/users/mohdjaved291/followers",
"following_url": "https://api.github.com/users/mohdjaved291/following{/other_user}",
"gists_url": "https://api.github.com/users/mohdjaved291/gists{/gist_id}",
"starred_url": "https://api.github.com/users/mohdjaved291/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/mohdjaved291/subscriptions",
"organizations_url": "https://api.github.com/users/mohdjaved291/orgs",
"repos_url": "https://api.github.com/users/mohdjaved291/repos",
"events_url": "https://api.github.com/users/mohdjaved291/events{/privacy}",
"received_events_url": "https://api.github.com/users/mohdjaved291/received_events",
"type": "User",
"site_admin": false
},
{
"login": "tabish1811",
"id": 87319414,
"node_id": "MDQ6VXNlcjg3MzE5NDE0",
"avatar_url": "https://avatars.githubusercontent.com/u/87319414?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/tabish1811",
"html_url": "https://github.com/tabish1811",
"followers_url": "https://api.github.com/users/tabish1811/followers",
"following_url": "https://api.github.com/users/tabish1811/following{/other_user}",
"gists_url": "https://api.github.com/users/tabish1811/gists{/gist_id}",
"starred_url": "https://api.github.com/users/tabish1811/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/tabish1811/subscriptions",
"organizations_url": "https://api.github.com/users/tabish1811/orgs",
"repos_url": "https://api.github.com/users/tabish1811/repos",
"events_url": "https://api.github.com/users/tabish1811/events{/privacy}",
"received_events_url": "https://api.github.com/users/tabish1811/received_events",
"type": "User",
"site_admin": false
},
{
"login": "codersaif",
"id": 89591257,
"node_id": "MDQ6VXNlcjg5NTkxMjU3",
"avatar_url": "https://avatars.githubusercontent.com/u/89591257?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/codersaif",
"html_url": "https://github.com/codersaif",
"followers_url": "https://api.github.com/users/codersaif/followers",
"following_url": "https://api.github.com/users/codersaif/following{/other_user}",
"gists_url": "https://api.github.com/users/codersaif/gists{/gist_id}",
"starred_url": "https://api.github.com/users/codersaif/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/codersaif/subscriptions",
"organizations_url": "https://api.github.com/users/codersaif/orgs",
"repos_url": "https://api.github.com/users/codersaif/repos",
"events_url": "https://api.github.com/users/codersaif/events{/privacy}",
"received_events_url": "https://api.github.com/users/codersaif/received_events",
"type": "User",
"site_admin": false
}
]