export default {
"login": "mehruddin11",
"id": 77490569,
"node_id": "MDQ6VXNlcjc3NDkwNTY5",
"avatar_url": "https://avatars.githubusercontent.com/u/77490569?v=4",
"gravatar_id": "",
"url": "https://api.github.com/users/mehruddin11",
"html_url": "https://github.com/mehruddin11",
"followers_url": "https://api.github.com/users/mehruddin11/followers",
"following_url": "https://api.github.com/users/mehruddin11/following{/other_user}",
"gists_url": "https://api.github.com/users/mehruddin11/gists{/gist_id}",
"starred_url": "https://api.github.com/users/mehruddin11/starred{/owner}{/repo}",
"subscriptions_url": "https://api.github.com/users/mehruddin11/subscriptions",
"organizations_url": "https://api.github.com/users/mehruddin11/orgs",
"repos_url": "https://api.github.com/users/mehruddin11/repos",
"events_url": "https://api.github.com/users/mehruddin11/events{/privacy}",
"received_events_url": "https://api.github.com/users/mehruddin11/received_events",
"type": "User",
"site_admin": false,
"name": "mehruddin khan",
"company": null,
"blog": "",
"location": null,
"email": null,
"hireable": null,
"bio": "full stack  developer\r\n",
"twitter_username": null,
"public_repos": 30,
"public_gists": 0,
"followers": 5,
"following": 8,
"created_at": "2021-01-15T11:35:59Z",
"updated_at": "2021-08-30T09:27:08Z"
}